
# general user input
raw_data:
  - "raw-data"
  - "raw-data2"
metadata: "metadata.tsv"
taxa_db: "classifier.fa"
output_dir: "applecorn-run"
images_dir: "images"
report_fn: "report.Rmd"
rarefy: false
mk_plots: false
mk_plots_ly: false
test_var: "treat"
r_data_dir: "data"
filt_path: "filtered"

# asv detection
suffix: "_R1,_R2"
split: "_L"
extn: "fastq.gz"
trim_left:
  - 26
  - 22
trunc_len:
  - 237
  - 202
max_ee:
  - 2
  - 2
dada_large: false # use to flag a large data set i.e very deep sequencing

# phylogenetic tree fit
# NOTE currently I only filter out outlier branches from ps object
# i.e after building a phylogenetic tree I can look for branches that don't fit the tree
# if I don't have the tree I can't really do any filtering.
# This means fit_tree and ps_filt at this stage are the same and fit_tree is therefore redundant
# but I'm using fit_tree elsewhere, so will keep it in for now
fit_tree: false
# phyloseq
ps_filt: true

# ordinations
dist_binary: "unifrac" #jaccard
dist_abund: "wunifrac" #bray

# taxonomic barplot
legend: "none" # bottom, left, right
n_taxa: 12 # N most abundance or NULL to plot all taxa
ncol: null # this will be passed to facet_wrap(ncol = ncol)

# other
debug: false
kraken_filt: false
kraken_contams_fn: "contams.txt"
