
# general user input
raw_data:
  - "raw-data"
  - "raw-data2"
metadata: "metadata.tsv"
taxa_db: "classifier.fa"
output_dir: "applecorn-run"
report_fn: "report.Rmd"
rarefy: false
mk_plots: false
test_var: "treat"
r_data_dir: "data"
filt_path: "filtered"

# asv detection
suffix: "_R1,_R2"
split: "_L"
extn: "fastq.gz"
trim_left:
  - 26
  - 22
trunc_len:
  - 237
  - 202
max_ee:
  - 2
  - 2

# phyloseq
ps_filt: true

# ordinations
dist_binary: "unifrac" #jaccard
dist_abund: "wunifrac" #bray

# taxonomic barplot
legend: "none" # bottom, left, right
n_taxa: 12 # N most abundance or NULL to plot all taxa
# other
debug: false
kraken_filt: false
kraken_contams_fn: "contams.txt"
